version: '3.1'
services:
  zk1:
    image: zookeeper
    hostname: zk1
    ports:
      - 2181:2181
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1:zk1:2888:3888 server.2=zk2:2888:3888
  zk2:
    image: zookeeper
    hostname: zk2
    ports:
      - 2182:2181
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1:zk1:2888:3888 server.2=zk2:2888:3888
  kafka:
    image: hilios/kafka:0.11.0.0
    ports:
      - 9092:9092
    links:
      - zk1
      - zk2
    command:
      - --override
      - broker.id=0
      - --override
      - advertised.listeners=PLAINTEXT://localhost:9092
      - --override
      - zookeeper.connect=zk1:2181,zk2:2182
      - --override
      - offsets.topic.replication.factor=1
